### PR TITLE
LSPS1: Remove human-readable `message` fields, describe error object.

### PR DESCRIPTION
**Pull request by ZmnSCPxj-jr**

### CODE REVIEW

**Comment by SeverinAlexB** [comment]
Thx for the contribution. I have a general question about the strategy we will be using to define API boundaries. Let me define `reactive` and `proactive` before I get into it:

## Reactive

The api responds with an error code after validating the request. This is the approach you are taking here.

Example error codes:
- `CLIENT_BALANCE_TOO_LOW`
- `CLIENT_BALANCE_TOO_HIGH`

## Proactive

We define the api boundaries before the order is created in the `GET /lsp/channels` response.

The current `GET /lsp/channels` response already includes some boundaries (for example `max_lsp_balance_satoshi`) but they seem insufficient.

```JSON
{
  "version": 2,
  "website": "http://example.com/contact",
  "options": {
    "base_api": {
      "version": 1,
      "max_user_balance_satoshi": "0",
      "max_lsp_balance_satoshi": "100000000",
      "min_required_onchain_satoshi": null,
      "max_channel_expiry_weeks": 24
    }
  }
}
```
## Issues

I see the proactive approach as superior because a wallet can enforce the boundaries in the UI before the order creation. Of course, request validation and therefore a `BAD_REQUEST` error code is still required. If we go with the proactive model though we might not need to detail every different boundary case like `CLIENT_BALANCE_TOO_LOW` or `CLIENT_BALANCE_TOO_HIGH`.

What do you think?

**Comment by ZmnSCPxj-jr** [comment]
Why not both?

We can consider that there is always a possibility of policy change (i.e. change of limits the LSP allows) between the `GET` and the later `POST`, so the "reactive" form handles that (i.e. client performs `GET`, LSP changes its policies on what limits it accepts, client performs `POST` that is inside the old policy but outside the new policy, LSP responds with specific error).

**Comment by SeverinAlexB** [comment]
We can have both. Do you want to sync up the proactive options and the errors?

**Comment by ZmnSCPxj-jr** [comment]
Could do that.

**Comment by SeverinAlexB** [comment]
Do you have any objections of me taking over this work here? @ZmnSCPxj-jr

**Comment by ZmnSCPxj-jr** [comment]
@SeverinAlexB no objections, sorry for the late reply.

**Comment by SeverinAlexB** [comment]
@ZmnSCPxj-jr Thx

**Comment by SeverinAlexB** [comment]
Closing because changes have been applied to LSPS1 PR.

**Pull request closed without merging**
